src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private int $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Regex(pattern="/^[[:alnum:]]([-_.]?[[:alnum:]])+_?@[[:alnum:]]([-.]?[[:alnum:]])+\.[a-z]{2,6}$/",
     * match=true, message="Entrez une adresse email valide")
     */
    private string $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private string $password;

    /**
     * @ORM\Column(type="string", length=45)
     * @Assert\Regex(pattern="/\d/", match=false, message="Votre prénom de peut pas contenir de chiffres")
     * @Assert\Regex(pattern="/^[a-zA-Zàâéèêîïôûù ]+$/", match=true, message="Les caractères spéciaux sont interdits")
     */
    private string $first_name;

    /**
     * @ORM\Column(type="string", length=45)
     * @Assert\Regex(pattern="/\d/", match=false, message="Votre prénom de peut pas contenir de chiffres")
     * @Assert\Regex(pattern="/^[a-zA-Zàâéèêîïôûù ]+$/", match=true, message="Les caractères spéciaux sont interdits")
     */
    private string $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private string $picture;

    /**
     * @ORM\Column(type="datetime")
     */
    private \Datetime $dob;

    /**
     * @ORM\Column(type="string", length=30)
     * @Assert\Regex(pattern="/^(?:(?:\+|00)33{0,3}(?:\(0\){0,3})?|0)[1-9](?:(?:\d{2}){4}|\d{2}(?:\d{3}){2})$/", 
     * match=true, message="Veuillez entrer un numéro valide sans aucun espace ni caractères")
     */
    private string $user_phone;

    /**
     * @ORM\Column(type="string", length=4)
     * @Assert\Regex(pattern="/^[a-zA-Z0-9 ,.'()-]+$/", match=true, message="Veuillez entrez un numéro valide")
     */
    private string $address_number;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private string $address_type;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex(pattern="/^[a-zA-Z 0-9,.'ÀÁÂÃÄÅàáâãäåÒÓÔÕÖØòóôõöøÈÉÊËèéêëÇçÌÍÎÏìíîïÙÚÛÜùúûüÿÑñ-]+$/", 
     * match=true, message="Veuillez entrez un nom valide")
     */
    private string $address_name;

    /**
     * @ORM\Column(type="string", length=15)
     * @Assert\Regex(pattern="/^[a-zA-Z0-9 ,.'()-]+$/", match=true, message="Veuillez entrez un code postal valide")
     */
    private string $address_zipcode;

    /**
     * @ORM\Column(type="string", length=120)
     * @Assert\Regex(pattern="/^[a-zA-Z ,.'()ÀÁÂÃÄÅàáâãäåÒÓÔÕÖØòóôõöøÈÉÊËèéêëÇçÌÍÎÏìíîïÙÚÛÜùúûüÿÑñ-]+$/", 
     * match=true, message="Veuillez entrez un nom de ville valide")
     */
    private string $address_city;

    public function __toString()
    {
        return $this->first_name;
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getEmail(): string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getPicture(): string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getDob(): \DateTime
    {
        return $this->dob;
    }

    public function setDob(\DateTime $dob): self
    {
        $this->dob = $dob;

        return $this;
    }

    public function getUserPhone(): string
    {
        return $this->user_phone;
    }

    public function setUserPhone(string $user_phone): self
    {
        $this->user_phone = $user_phone;

        return $this;
    }

    public function getAddressNumber(): string
    {
        return $this->address_number;
    }

    public function setAddressNumber(string $address_number): self
    {
        $this->address_number = $address_number;

        return $this;
    }

    public function getAddressType(): string
    {
        return $this->address_type;
    }

    public function setAddressType(string $address_type): self
    {
        $this->address_type = $address_type;

        return $this;
    }

    public function getAddressName(): string
    {
        return $this->address_name;
    }

    public function setAddressName(string $address_name): self
    {
        $this->address_name = $address_name;

        return $this;
    }

    public function getAddressZipcode(): string
    {
        return $this->address_zipcode;
    }

    public function setAddressZipcode(string $address_zipcode): self
    {
        $this->address_zipcode = $address_zipcode;

        return $this;
    }

    public function getAddressCity(): string
    {
        return $this->address_city;
    }

    public function setAddressCity(string $address_city): self
    {
        $this->address_city = $address_city;

        return $this;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserFormType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/user')]
class UserController extends AbstractController
{
    #[Route('/', name: 'user')]
    public function index(UserRepository $userRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $user = $this->getUser();

        if ($user->getRoles()[0] == 'ROLE_ADMIN') {

            $userRepository = $this->getDoctrine()->getRepository(User::class);
            $users = $userRepository->findAll();

            return $this->render('user/index.html.twig', [
                'users' => $users,
            ]);
        } else {
            $this->addFlash('danger', 'Accès refusé, vous n\'êtes pas l\'administrateur !');
            return $this->redirectToRoute('index');
        }
    }

    #[Route('/view/{id}', name: 'user_view')]
    public function view(UserRepository $userRepository, $id): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $user = $this->getUser();
        $userRepository = $this->getDoctrine()->getRepository(User::class);

        if ($user->getRoles()[0] == 'ROLE_ADMIN') {
            $userView = $userRepository->find($id);
            if (!$userView) {
                $this->addFlash('danger', 'utilisateur inexistant avec l\'id : ' . $id);
                return $this->redirectToRoute('user');
            }
        } else {
            $userView = $userRepository->find($user->getId());
        }

        return $this->render(
            'user/view.html.twig',
            [
                'user' => $userView
            ]
        );
    }

    #[Route('/update/{id}', name: 'user_update', methods: ['GET', 'POST'])]
    public function update(User $user, Request $request, $id): Response
    {
    
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        if($this->isCsrfTokenValid('update' . $user->getId(), $request->request->get('token'))) {
            $userConnect = $this->getUser();
            $user = $this->getDoctrine()->getRepository(User::class)->find($id);
    
            if ($userConnect->getRoles()[0] == 'ROLE_ADMIN') {
                if ($user) {
    
                    $form = $this->createForm(UserFormType::class, $user);
                    $form->handleRequest($request);
    
                    if ($form->isSubmitted() && $form->isValid()) {
                        $phone = $form->get('user_phone')->getData();
                        $phone = wordwrap($phone, 2, ' ', true);
                        $user->setUserPhone($phone);

                        $nom = $user->getLastName();
                        $prenom = $user->getFirstName();
                        $ville = $user->getAddressCity();
                        $user->setLastName(strtoupper($nom))
                            ->setFirstName(strtoupper($prenom))
                            ->setAddressCity(strtoupper($ville));

                        try {
                            $this->getDoctrine()->getManager()->flush();
                        } catch (Exception $e) {
                            throw new HttpException(500, 'Erreur lors de l\'enregistrement de la modification');
                        }
                        return $this->redirectToRoute('user_view', ['id' => $user->getId()]);
                    }
    
                    return $this->render(
                        'user/formUpdate.html.twig',
                        [
                            "user" => $user,
                            "updateForm" => $form->createView()
                        ]
                    );
                } else {
                    throw $this->createNotFoundException('utilisateur inexistant avec l\'id' . $id);
                }
            } else {
                $this->addFlash('danger', 'pas admin');
                return $this->redirectToRoute('index');
            }
            return $this->redirectToRoute('user'); 
        }
        return $this->redirectToRoute('user_view', ['id' => $user->getId()]);
    }

    #[Route('/delete/{id}', name: 'user_delete', methods: ['GET', 'POST'])]
    public function delete(User $user, Request $request, EntityManagerInterface $em): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        if ($user) {
            if ($this->isCsrfTokenValid('delete' . $user->getId(), $request->request->get('token'))) {

                try {
                    $em->remove($user);
                    $em->flush();
                } catch (Exception $e) {
                    $this->addFlash('danger', 'Suppression impossible');
                    return $this->redirectToRoute('user');
                }
            }
        }
        return $this->redirectToRoute('user');
    }
}

templates/user/_delete.html.twig
<form action="{{ path('user_delete', {id: user.id}) }}" method = "post"  
    onsubmit="return confirm('Vous êtes sur le point de supprimer un utilisateur, confirmer ?');">
        
        <input type="hidden" name="token" value="{{ csrf_token('delete' ~ user.id) }}">
        <button title= "Supprimer l'utilisateur" type="submit">Supprimer</button>
</form>

templates/user/_update.html.twig
<form action="{{path('user_update', {id: user.id}) }}" method="post">
    <input type="hidden" name="token" value="{{ csrf_token('update' ~ user.id )}}"/>

    <button title="Modifier l'utilisateur" type="submit">Modifier</button>
</form>

templates/user/formUpdate.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{parent()}}
	Modification fiche client
{% endblock %}

{% block body %}
	<div class="row">
		<div class="row-custom">
			{% form_theme updateForm 'bootstrap_4_layout.html.twig' %}

			{{ form_start(updateForm) }}
			{{ form_widget(updateForm) }}
			{{ form_start(updateForm) }}

		</div>
	</div>
		{% if app.user and app.user == user or is_granted('ROLE_ADMIN')%}
			<div class="row-update-user">
				<div class="">
					{% include('user/_update.html.twig') %}
				</div>
				<div class="">
					{% include('user/_delete.html.twig') %}
				</div>
				<a title="Retour à la page précédente" class="btn-retour" href="{{path('user')}}">
					<i class="fas fa-arrow-alt-circle-left"></i>Retour</a>
			</div>
		{% endif %}
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{parent()}}
	Liste des clients
{% endblock %}

{% block body %}
{% include('_flash.html.twig') %}
	<div class="clients">
		<h2>Clients</h2>
		<table class="table">
			<thead>
				<tr>
					<th>NOM-Prénom</th>
					<th>Adresse</th>
					<th>Email</th>
					<th>Téléphone</th>
					<th>Actions</th>
				</tr>
			</thead>

			<tbody>
				{% for user in users %}
					<tr>
						<td>{{user.lastName }}-{{user.firstName }}</td>
						<td>{{user.addressNumber}},{{user.addressType}}
							{{user.addressName}}-{{user.addressZipCode}},{{user.addressCity}}</td>
						<td>{{user.email}}</td>
						<td>{{user.userPhone}}</td>
						<td>
							<button title= "Afficher la fiche du client"id="index-user" type="submit">
								<a title= "Afficher la fiche du client" class="link" href={{ path('user_view', {id: user.id} ) }}>afficher</a>
							</button>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
{% endblock %}

templates/user/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{parent()}}
	Client :
	{{user.lastName}}
	-
	{{user.firstName}}
{% endblock %}

{% block body %}
	<div class="row row-custom ">
		<div class= "card" style="width: 18vw;">
			<div class="card-user">
				<img src="{{ asset('uploads/' ~ user.picture) }}" alt="photo de l'utilisateur" class="card-img-top user-picture">
				<h2 class="card-title">
					{{user.lastName}}
					-
					{{user.firstName}}
				</h2>
				<div class="card-body cardbody">
					<p class="card-text">{{user.addressNumber}},{{user.addressType}}
						{{user.addressName}}-{{user.addressZipCode}},{{user.addressCity}}</p>
					<p class="card-text">{{user.dob | date("m/d/Y")}}</p>
					<p class="card-text">{{user.email}}
					<p class="card-text">{{user.userPhone}}</p>	


				</div>
			</div>
		</div>

					{% if app.user and app.user == user or is_granted('ROLE_ADMIN')%}
						<div class="row-update-user">

							<div class="row">
								<div class="btn-coin ">
									<div class="btn-coin">
										{% include('user/_update.html.twig') %}
										{% include('user/_delete.html.twig') %}
										<a title="Retour à la page précédente" class="btn-retour" href="{{path('user')}}">
											<i class="fas fa-arrow-alt-circle-left"></i>Retour</a>
									</div>
								</div>
							</div>

							{% else %}
								<div class="btn-coin">
									<div class="btn-coin">
										<a title="Prendre un rendez-vous" href="{{path('lieu_rdv')}}" class="btn btn-custom btn-prendre-rdv">Prendre rdv</a>
										<a title="Retour à la page précédente" href="{{path('user')}}" class="btn-retour">
											<i class="fas fa-arrow-alt-circle-left"></i>Retour</a>
									</div>
								</div>
						</div>
					{% endif %}

	</div>
{% endblock %}